### ISSUE TITLE
Request information about X8000 (connect to Google Sheets)

### ISSUE THREAD

**Issue by LucaCretier** [brego81/Legrand-Bticino-Python-API#1]
Hi,
my name is Luca and I write for request informations. I have two chronotermostat in my home (https://faidate.bticino.it/it/soluzioni-da-vivere/smart-home/smarther-termostato-connesso/) and I want to collect data (temperature, humidity and on/off - if possible). I have another sensor (Sonoff TH16) and I have find a solution to collect data and write them in Google Sheets (https://community.smartthings.com/t/release-simple-event-logger/69879). After this I'm able to create chart with Google Data Studio.

I want to find a solution for my chronotermostats but I'm only able to connect them with Google Home. I have find another solution but require Raspberry (https://hassiohelp.eu/2020/05/01/bticino-smarther-x8000/). Maybe there is a solution with Google Script or with free Python Server Online (https://www.pythonanywhere.com) but I'm not a programmer...

Can you help me? I have open a topic on Legrand Forum but I don't have any response (https://developer.legrand.com/forums/topic/request-help-to-connect-smarther-sx8000-with-other-app/).

Sorry for the request
and 
best regards,
Luca

**Comment by brego81** [comment]
Hi Luca and thanks for writing.
If I understand correctly you need to collect data from your
chronotermostats and save it down to a Google docs.
I guess you would like to pick the data every 5 minutes or so in order to
keep track of what happened.

This can be easily achieved using my repository since it is something I am
also doing, however you need one of this:
- a PC ( may be an old PC or a raspberry) that remains on and collects and
store data.
- a Google Cloud compute engine that is almost free (
https://cloud.google.com/free/docs/gcp-free-tier/#compute)

If you think you can allocate one of the above two options, I am happy to
provide further details on how to get everything up and running

Best regards,
Matteo

**Comment by LucaCretier** [comment]
Hi Matteo,
thank you for your help. Yes, you understand correctly: I need to collect
data from two chronotermostats in my home and save in Google Sheets and
every X minutes (15 is ok). At the moment I store my data in Google Sheets
(FR9M Son9ff TH16) and visualize in Google Data Studio.

I have activate free version of Google Cloud because I don't have old PC /
Raspberry. Thank you a lot :)


Ciao
Luca


Il Sab 8 Gen 2022, 10:06 Matteo Bregonzio ***@***.***> ha
scritto:

> Hi Luca and thanks for writing.
> If I understand correctly you need to collect data from your
> chronotermostats and save it down to a Google docs.
> I guess you would like to pick the data every 5 minutes or so in order to
> keep track of what happened.
>
> This can be easily achieved using my repository since it is something I am
> also doing, however you need one of this:
> - a PC ( may be an old PC or a raspberry) that remains on and collects and
> store data.
> - a Google Cloud compute engine that is almost free (
> https://cloud.google.com/free/docs/gcp-free-tier/#compute)
>
> If you think you can allocate one of the above two options, I am happy to
> provide further details on how to get everything up and running
>
> Best regards,
> Matteo
>
>

**Comment by brego81** [comment]
Cool, I think you have all you needed.
As far as I understand you are not familiar with python and programming
languages, correct?

If so the fastest way is to scheduled a 30 mins hangout call to set up the
environment. Once it si done you will see data feeding your Google sheet.

If you share your Gmail address I will book a call
Regards
Matteo

**Comment by LucaCretier** [comment]
Hi,
yes, I'm not familiar with Python and programming (I write little macro
with VBA, for Excel, but very simple).

Thank you one more time: here my address
luca.cretier AT gmail DOT com


Bye
Luca

Il Dom 9 Gen 2022, 09:42 Matteo Bregonzio ***@***.***> ha
scritto:

> Cool, I think you have all you needed.
> As far as I understand you are not familiar with python and programming
> languages, correct?
>
> If so the fastest way is to scheduled a 30 mins hangout call to set up the
> environment. Once it si done you will see data feeding your Google sheet.
>
> If you share your Gmail address I will book a call
> Regards
> Matteo
>

**Comment by brego81** [comment]
closing issue.
